### ISSUE TITLE
Access is denied on `ProMicro_PCB` link in Lily58 pro guide

### ISSUE THREAD

**Issue by MiConnell** [keyhive/build_guides#4]
The below link on the Lily58 Pro build guide results in an access denied error in the [install pro micro section](https://github.com/keyhive/build_guides/blob/master/lily58pro.md#install-pro-micro)

https://user-images.githubusercontent.com/6285554/4891967-6a599a80-ed94-11e8-8e5d-6a6abca326a7.png

![Screen Shot 2021-01-04 at 12 09 17 PM](https://user-images.githubusercontent.com/14168559/103574942-afae8880-4e85-11eb-9ee5-ad2d937f0e4b.png)

**Comment by filoxo** [comment]
This means that the image was deleted from whatever repo it was hosted in. There isn't much to be done on our end other than delete the image tag which I've done in https://github.com/keyhive/build_guides/pull/6.
